### ISSUE TITLE
read CC environment variable

### ISSUE THREAD

**Issue by luarockr** [vishaps/voc#68]
maybe it would make sense to read the CC environment variable to allow c compilers other than gcc or to allow providing optimization flags to the c compiler.

**Comment by norayr** [comment]
we read CFLAGS to customize C compiler flags.

what about CC, formerly we were just using CC, but apparently it's not enough to just set CC, CFLAGS, and type sizes. if you look at src/tools/make/configure.c, you'd see that there are supported compilers other than gcc, and that there are many specifics that should be handled.

so I would say, if you want to run voc on the unsupported platform, file a ticket.

we already have some lines in code that keep in mind that the compiler might be used wth avr gcc or sdcc.

but no ready to use target yet.

anyway, the existing codebase covers almost everything possible, it should run on all Unix systems (I think only AIX/PowerPC is unsupported due to its big endian nature), and Windows.

and you cannot use tcc to compile this complex code.

**Comment by luarockr** [comment]
Thanks a lot for the hint with the CFLAGS, works fine for me. Alternatively, to use different C compilers, could write a Makefile using voc -S and compiling generated C code manually in it (or via shell command manually).
Great work on voc, loving it :-)
