### ISSUE TITLE
showdef Out -- symbol file not found

### ISSUE THREAD

**Issue by jkleiser** [vishaps/voc#76]
I followed the suggestion I got after the compiler was built, adding `export PATH="/Volumes/P3/Vishap_Oberon/voc/install/bin:$PATH"` to my `~/.bash_profile`, and opened a new Terminal window (on macOS). Then compiling a simple hello.mod (that makes use of `IMPORT Out;`), outside the voc folder, works fine. However, if I try `showdef Out` in the same folder, I get `Out -- symbol file not found`. I would have expected that showdef should find the same stuff that the voc compiler is able to find.

**Comment by dcwbrown** [comment]
Well found! It turns out that showdef looks in the location that ```make install``` writes to. As you say it ought really to be using exactly the same logic as the compiler does.

So the workaround is to run

   ```sudo make install```

from the voc directory. (Then you will probably want to change your path setting in .bash_profile to the new installed location which should be /opt/voc/bin.)

**Comment by jkleiser** [comment]
Thanks! That's what was missing. I just noticed from the docs. ;-)
